### ISSUE TITLE
question: E_loo weighted variance calculation

### ISSUE THREAD

**Issue by cfhammill** [stan-dev/loo#121]
Hi loo devs,

I'm a bit confused about the calculations for weighted variance. Following the the code leads to https://github.com/stan-dev/loo/blob/master/R/E_loo.R#L200

```r
.wvar <- function(x, w, r_eff = NULL, ...) {
  if (is.null(r_eff)) {
    r_eff <- 1
  }
  r <- (x - .wmean(x, w))^2
  sum(w^2 * r) / r_eff
}
```

I'm curious why the weights are squared in the summation. https://en.wikipedia.org/wiki/Weighted_arithmetic_mean#Weighted_sample_variance shows the same calculation with the unsquared weights (for variance without the Bessel correction).  I also found an R function example with the correction if that's of interest https://stat.ethz.ch/pipermail/r-help/2008-July/168762.html

**Comment by yao-yl** [comment]
Hi Chris,
I think these are two different tasks:
1)unsquared weights:
if we sample x from q and there is another p, we will compute the weights
p/q and adjust the *population* variance by the weights w=p/q. This is
effectively to use compute the population variance via importance sampling.
2) squared weighs
the *sample* variance of a weighted sum, has a factor w^2, due to the
simple relation Var(wX)=w^2 Var(X).  This can be understood as the
variance of importance sampling.
Yuling

**Comment by cfhammill** [comment]
That makes sense now, thanks Yuling!

**Comment by jgabry** [comment]
should we add the formulas to the doc?
