### ISSUE TITLE
License for the documentation?

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#175]
The loo repo has only GPL-3 license. @aloctavodia asked to re-use LOO glossary. Maybe we should add also explicit CC license for the text content? Stan manual is with CC-BY ND 4.0 license. What do you think? Ping @jgabry

**Comment by jgabry** [comment]
Yeah that sounds good to me. Should we add a License section to the readme that mentions this difference between code and doc?

And since we're on the topic of licenses, we have a relatively small number of people who have contributed code to loo, so we could potentially get everyone's permission to change the license for the whole repository from GPL-3 to something more permissive like BSD-3 or MIT if there's interest in that

**Comment by avehtari** [comment]
> Should we add a License section to the readme that mentions this difference between code and doc?

Yes. And add the doc license to the LICENSE file (as in https://github.com/stan-dev/docs/blob/master/LICENSE)
It seems other Stan repos also don't explicitly mention in README that doc is CC, but for example Stan users guide https://mc-stan.org/docs/2_26/stan-users-guide/index.html does expclicitly mention CC-BY ND 4.0, and many case studies (at least those made by Bob) explicitly mention license for code and text separately,

**Comment by avehtari** [comment]
@jgabry reminding about this which should be easy to fix

Adding that Stan users guide might switch from CC-BY-ND to CC-BY, so CC-BY would be good for the documentation in his package, too
