### ISSUE TITLE
Add support for `cmdstanr` models to the `extract_log_lik` function

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/loo#207]
Some feedback came through from the BDA course was the inability to use the `extract_log_lik` functionswith `cmdstanr` model objects, which was a bit confusing for the student following a tutorial which used `rstan`

**Comment by jgabry** [comment]
Yeah I can see that being confusing. In hindsight I think it was probably a mistake to put `extract_log_lik` in the loo package in the first place. That was before we had a `loo` method for stanfit objects in the RStan package and users need to get the log lik matrix and pass it to the loo package themselves. I wonder if we should add support for CmdStanR objects or just deprecate the `extract_log_lik` function and point users to loo methods in the model fitting packages. Thoughts?

**Comment by avehtari** [comment]
>  I wonder if we should add support for CmdStanR objects

I vote for this.

>  or just deprecate the extract_log_lik function and point users to loo methods in the model fitting packages

While it's nice that CmdStanr has `fit$loo()` method, it is confusing that it doesn't work with `loo(fit)` when coming from RStan, so it would be nice to allow `loo(fit)` for CmdStanR objects, too. And then we could also deprecate `exctract_log_lik`

**Comment by avehtari** [comment]
@andrjohns and @jgabry , do we need to do something for this? This year in BDA course, we have just been teaching `fit$loo()`

**Comment by jgabry** [comment]
Going through old issues and I found this. I'm going to close this because if we want to add the ability to do `loo(fit)` for cmdstanr models then that would need to be done in the cmdstanr package. If your students were ok with the `fit$loo()` syntax then I don't think we should add anything to cmdstanr. But if the students were very confused about having to do `fit$loo()` then we add the ability to do `loo(fit)`. In that case let me know and we can open an issue for this in cmdstanr. It would be easy to implement, but the way the cmdstanr documentation works it could be a little bit confusing to document both ways of doing loo. 

Anyway, closing this but let me know if you want to reopen it in cmdstanr instead.
