### ISSUE TITLE
Error message when using compare_models function for loo objects

### ISSUE THREAD

**Issue by alissab** [stan-dev/loo#54]
I'm using the `compare_models` function on `loo` objects in rstanarm, and receiving an error message I don't understand. All the models I'm comparing use the same dataset (same # observations, same response variable, same family of distributions, same transformation applied to the response variable), but when I call `compare_models`, I receive the following error message:

> Error: Not all models have the same y variable.

Full description of the problem is here: http://discourse.mc-stan.org/t/error-message-when-using-compare-models-function-for-loo-objects-of-hierarchical-models/3008

And the link to my R project (with .RData and .R files) is here: https://www.dropbox.com/sh/jdmjy2w55fd24pm/AABL0Q4Myl9rA38F850AGmUTa?dl=0

**Comment by avehtari** [comment]
loo in rstanarm checks that the user doesn't compare models which used different data (easy to make mistake especially if you try to compare a model fitted with `y` to a model fitted with `log(y)', as this requires information not necessarily directly available for loo/rstanarm).

In order to save some memory loo computes a hash of y and compares these hashes. You can check that hash with
```
attr(l_gr_full_5,"yhash")
attr(l_gr_rslope_5,"yhash")
```

Now in your models y is `growth`, and it is same (in your saved file)
```
> identical(gr_full_5$glmod$fr$growth,rslope_5$glmod$fr$growth)
[1] TRUE
```
For some unknown reason in your saved file the loo object `l_gr_rslope_5` had a different hash than the other loo objects. If I rerun `loo` for other models I get the same hash as in the  loo object `l_gr_rslope_5` and comparison works (note that comparing more than 2 models doesn't give correct pairwise comparison results).

Did you run some of the models first, saved the results, changed something and then made the slope rslope_5 model? Could you try rerunning loo for the models and check `yhash' for all loo objects?

**Comment by alissab** [comment]
> Did you run some of the models first, saved the results, changed something and then made the slope rslope_5 model?

Yes! You have found the problem. I re-ran `loo` for all models and it worked. 

Does this mean that anytime I compare models using `loo` I should do so in the same R session?

**Comment by avehtari** [comment]
I would assume hash should be same in different sessions in general, but it's possible that if R version of the package version used to compute hash has changed that there is difference.

@jgabry how is hash computed and do you have idea why the hash can be different in different sessions?

**Comment by jgabry** [comment]
Interesting. I would also assume that the hashes should be the same even in different sessions. We certainly don't want to prevent people from comparing models run in different R sessions! I just did a few tests that confirm that I get the same hash in different sessions and I also checked that I can save the loo objects created in different sessions and then compare them, so I'm not sure what the issue was here. We use the `digest` package to create the hashes and maybe @avehtari is right and the hashes changed when a new version came out. But that would also be surprising.

**Comment by alissab** [comment]
Thanks so much for addressing this. I tried updating to the most recent version of `rstanarm` (2.17.2), had problems with it, then re-installed the version I was working with before (2.15.2). There is a possibility that in the confusion of things, I ended up using a different `rstanarm` version for some `loo` objects than others (I'm not sure if this would cause the issue, though). Thanks again!
